/*
 * URL Shortener
 *
 * A url shortener, written in Go running on Kubernetes
 *
 * API version: 1.0
 * Contact: urlshortener-api@cedi.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1ShortLinkSpec struct {
	// RedirectAfter specifies after how many seconds to redirect (Default=3) +kubebuilder:default:=0 +kubebuilder:validation:Minimum=0 +kubebuilder:validation:Maximum=99
	After int32 `json:"after,omitempty"`
	// Code is the URL Code used for the redirection. leave on default (307) when using the HTML behavior. However, if you whish to use a HTTP 3xx redirect, set to the appropriate 3xx status code +kubebuilder:validation:Enum=200;300;301;302;303;304;305;307;308 +kubebuilder:default:=307
	Code int32 `json:"code,omitempty"`
	// Owner is the GitHub user name which created the shortlink +kubebuilder:validation:Required
	Owner string `json:"owner,omitempty"`
	// Co-Owners are the GitHub user name which can also administrate this shortlink +kubebuilder:validation:Optional
	Owners []string `json:"owners,omitempty"`
	// Target specifies the target to which we will redirect +kubebuilder:validation:Required +kubebuilder:validation:MinLength=1
	Target string `json:"target,omitempty"`
}
