/*
 * URL Shortener
 *
 * A url shortener, written in Go running on Kubernetes
 *
 * API version: 1.0
 * Contact: urlshortener-api@cedi.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ControllerShortLink struct {
	Name string `json:"name,omitempty"`
	Spec *V1alpha1ShortLinkSpec `json:"spec,omitempty"`
	Status *V1alpha1ShortLinkStatus `json:"status,omitempty"`
}
